server.port=8080

logging.level.com.bajaj.health.bfhl=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

app.user.fullname=${APP_USER_FULLNAME}
app.user.dob=${APP_USER_DOB}
app.user.email=${APP_USER_EMAIL}
app.user.rollnumber=${APP_USER_ROLLNUMBER}