server.port=8080

logging.level.com.bajaj.health.bfhl=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

app.user.fullname=Trisha_PALIWAL
app.user.dob=15112005
app.user.email=trishapaliwal231386@acropolis.in
app.user.rollnumber=0827CS231277