# Server Port Configuration
server.port=8080

# Logging Configurations
logging.level.com.bajaj.health.bfhl=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Core User Details Configuration
# Replace these with your actual details as requested
app.user.fullname=john_doe
app.user.dob=17091999
app.user.email=john@xyz.com
app.user.rollnumber=ABCD123
